name: IA Autônoma - Deploy no GitHub Pages

on:
  push:
    branches: ["main"]  # roda quando tiver commit na branch main
  schedule:
    - cron: "0 * * * *" # roda a cada 1 hora automaticamente
  workflow_dispatch:     # permite rodar manualmente também

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install openai gitpython

      - name: Rodar script da IA
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python script.py

      - name: Configurar Pages
        uses: actions/configure-pages@v4

      - name: Upload de artefatos
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public   # a IA deve salvar o site dentro dessa pasta

      - name: Deploy no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
